[deps]
DistributedArrays = "aaf54ef3-cdf8-58ed-94cc-d582ad619b94"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
MatrixMarket = "4d4711f2-db25-561a-b6b3-d35e7d4047d3"
SparseMatricesCSR = "a0a7dd2c-ebf4-11e9-1f05-cf50bc540ca1"

[MPIPreferences]
__clear__ = ["libmpi", "abi", "mpiexec", "cclibs", "preloads_env_switch"]
_format = "1.0"
binary = "OpenMPI_jll"
preloads = []

[extras]
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
